<a href="https://colab.research.google.com/github/Meshi1520/Deep-learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf
#keras is made on tesorflow keras make neural networks using tensorflow
from tensorflow import keras

In [ ]:
#do train test split

In [ ]:
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
import torch.nn as nn

In [ ]:
print(torch.__version__)

NameError: name 'torch' is not defined

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "soil_moisture": [0.20, 0.25, 0.30, 0.35,
                      0.40, 0.45, 0.50, 0.55,
                      0.60, 0.65, 0.70, 0.75,
                      0.80, 0.85, 0.90, 0.95],

    "temperature_c": [35, 33, 32, 30,
                      29, 28, 27, 26,
                      25, 24, 23, 22,
                      21, 20, 19, 18],

    "sunlight_hours": [10, 9, 9, 8,
                       8, 7, 7, 6,
                       6, 5, 5, 4,
                       4, 3, 3, 2],

    "needs_water": [1, 1, 1, 1,
                    1, 0, 0, 0,
                    0, 0, 0, 0,
                    0, 0, 0, 0]
})

print(df)

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.20             35              10            1
1            0.25             33               9            1
2            0.30             32               9            1
3            0.35             30               8            1
4            0.40             29               8            1
5            0.45             28               7            0
6            0.50             27               7            0
7            0.55             26               6            0
8            0.60             25               6            0
9            0.65             24               5            0
10           0.70             23               5            0
11           0.75             22               4            0
12           0.80             21               4            0
13           0.85             20               3            0
14           0.90             19               3            0
15           0.95             18               2            0

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.20             35              10            1
1            0.25             33               9            1
2            0.30             32               9            1
3            0.35             30               8            1
4            0.40             29               8            1
5            0.45             28               7            0
6            0.50             27               7            0
7            0.55             26               6            0
8            0.60             25               6            0
9            0.65             24               5            0
10           0.70             23               5            0
11           0.75             22               4            0
12           0.80             21               4            0
13           0.85             20               3            0
14           0.90             19               3            0
15           0.95             18               2            0

In [ ]:
X = df[['soil_moisture','temperature_c','sunlight_hours']]
y = df['needs_water']

In [ ]:
#we need to scale these values
#normalisation = 0 and 1
#standardization av = 0 and values are between -3 and +3

In [ ]:
#in dl we use normalisation using min max scaler
from sklearn.preprocessing import MinMaxScaler
X_scaled = MinMaxScaler().fit_transform(X)

In [ ]:
X_scaled

array([[0.        , 1.        , 1.        ],
       [0.06666667, 0.88235294, 0.875     ],
       [0.13333333, 0.82352941, 0.875     ],
       [0.2       , 0.70588235, 0.75      ],
       [0.26666667, 0.64705882, 0.75      ],
       [0.33333333, 0.58823529, 0.625     ],
       [0.4       , 0.52941176, 0.625     ],
       [0.46666667, 0.47058824, 0.5       ],
       [0.53333333, 0.41176471, 0.5       ],
       [0.6       , 0.35294118, 0.375     ],
       [0.66666667, 0.29411765, 0.375     ],
       [0.73333333, 0.23529412, 0.25      ],
       [0.8       , 0.17647059, 0.25      ],
       [0.86666667, 0.11764706, 0.125     ],
       [0.93333333, 0.05882353, 0.125     ],
       [1.        , 0.        , 0.        ]])

In [ ]:
df = pd.DataFrame(X_scaled, columns = ['soil_moisture','temperature_c','sunlight_hours'])

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours
0        0.000000       1.000000           1.000
1        0.066667       0.882353           0.875
2        0.133333       0.823529           0.875
3        0.200000       0.705882           0.750
4        0.266667       0.647059           0.750
5        0.333333       0.588235           0.625
6        0.400000       0.529412           0.625
7        0.466667       0.470588           0.500
8        0.533333       0.411765           0.500
9        0.600000       0.352941           0.375
10       0.666667       0.294118           0.375
11       0.733333       0.235294           0.250
12       0.800000       0.176471           0.250
13       0.866667       0.117647           0.125
14       0.933333       0.058824           0.125
15       1.000000       0.000000           0.000

In [ ]:
#IT PERFORMS well on such data like its just a blac box at this pointt

In [ ]:
train_test_split?

In [ ]:
X_train, X_test, y_train, y_test = train_test_split( X_scaled, y, test_size=0.25, stratify = y ,random_state=42)

In [ ]:
y

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
Name: needs_water, dtype: int64

In [ ]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    #for binary classification we are going to use sigmoid activation function
    layers.Dense(1,activation = 'sigmoid')
])

In [ ]:
model1 = nn.Sequential(
    nn.Linear((X_train.shape[1]),8),
    nn.ReLU(),
    nn.Linear(8,1),
    nn.Sigmoid()


)

In [ ]:
#we are going to use loss and optimizers
#now we compile
model.compile(optimizer = 'sgd', loss = 'binary_crossentropy',metrics = ['accuracy']) #simple gradient descent

In [ ]:
history = model.fit(
    X_train,y_train,
    validation_data = (X_test,y_test),
    epochs = 100,
    batch_size = 4,
    verbose = 0
)

In [ ]:
#loss this is the loss o training data
#this accuracy is on training accuarcy
#val_loss this is the loss validation loss it is the percentage of loss on test data to check ifthe model is not just learning values
#val_Accuracy how well the model is doing on unseen data

In [ ]:
from tensorflow.keras import optimizers

In [ ]:
opt = optimizers.SGD(learning_rate = 0.01,momentum = 0.9)